services:
  db:
    image: postgres:latest
    container_name: jester_db
    env_file:
      - .env
    ports:
      - "8000:5432"
    volumes:
      - jester_db_data:/var/lib/jester_postgresql/data

volumes:
  jester_db_data: